
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: "asrNuanceXhr",
  config: [
    /**
     * OPTIONAL
     * Indicates the source of the audio recording.
     * Properly specifying this header improves recognition accuracy.
     * Nuance encourages you to pass this header whenever you can -- and as accurately as possible.
     */
    "source",
    /** OPTIONAL  set recognition mode */
    "mode",
    /** OPTIONAL number of n-best results that should (max.) be returned: integer of [1, 10] */
    "results",
    /** OPTIONAL a persistent user pseudonym (should not be traceable/enable reverse-lookup of user); must be URI-encoded/conformant (e.g. user encodeURIComponent()) */
    "userId",
    /** credentials application key (MUST be set via configuration or options) */
    "appKey",
    /** credentials application ID (MUST be set via configuration or options) */
    "appId",
    /** OPTIONAL
     * @default "amr" (see mmir-plugin-encoder-core) */
    "encoder"
  ],
  remoteUrls: {
    baseUrl: "https://dictation.nuancemobility.net"
  }
};
